#!/bin/sh
set -e

echo "=== PREPARING CACHE FOLDERS ==="
mkdir -p $APP_PATH/vendor/bundle $APP_PATH/node_modules $APP_PATH/public

echo "=== INSTALLING DEPENDENCIES ==="
bundle install
yarn install

echo "=== CLEANING OLD DEPENDENCIES, ASSETS AND LOGS ==="
bundle clean

if [ ! -f "$HOME/.setup_complete" ]; then
  echo "=== SETTING UP PROJECT ==="
  #chsh -s /bin/zsh

  echo "=== INSTALLING OHMYZSH ==="
  if [ ! -d "$HOME/.oh-my-zsh" ]; then sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -) --unattended"; fi

  echo "=== SETTING UP DATABASE ==="
  rails db:create db:migrate db:seed

  touch "$HOME/.setup_complete"
fi

echo "=== APPLYING LATEST MIGRATIONS ==="
rails db:migrate

echo "=== STARTING WEB SERVER ==="
./bin/dev
